SLURM_JOB_ID: 64482694
SLURM_JOB_USER: vsc37097
SLURM_JOB_ACCOUNT: lp-emedia
SLURM_JOB_NAME: slurm_h100.sh
SLURM_CLUSTER_NAME: wice
SLURM_JOB_PARTITION: gpu_h100
SLURM_NNODES: 1
SLURM_NODELIST: s16g21
SLURM_JOB_CPUS_PER_NODE: 16
SLURM_JOB_GPUS: 0,3
Date: Tue May 13 05:09:15 CEST 2025
Walltime: 00-01:40:00
========================================================================

--- Running with smoothing: L1 ---

W0513 05:09:30.650000 2711919 /vsc-hard-mounts/leuven-data/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py:793] 
W0513 05:09:30.650000 2711919 /vsc-hard-mounts/leuven-data/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py:793] *****************************************
W0513 05:09:30.650000 2711919 /vsc-hard-mounts/leuven-data/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py:793] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0513 05:09:30.650000 2711919 /vsc-hard-mounts/leuven-data/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py:793] *****************************************
/data/leuven/370/vsc37097/miniconda3/envs/torch/bin/python: can't open file '/vsc-hard-mounts/leuven-data/370/vsc37097/thesis/dl_train.py': [Errno 2] No such file or directory
/data/leuven/370/vsc37097/miniconda3/envs/torch/bin/python: can't open file '/vsc-hard-mounts/leuven-data/370/vsc37097/thesis/dl_train.py': [Errno 2] No such file or directory
E0513 05:09:30.760000 2711919 /vsc-hard-mounts/leuven-data/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 2) local_rank: 0 (pid: 2711942) of binary: /data/leuven/370/vsc37097/miniconda3/envs/torch/bin/python
Traceback (most recent call last):
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/leuven/370/vsc37097/miniconda3/envs/torch/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
dl_train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-05-13_05:09:30
  host      : s16g21.tier2.hpc.kuleuven.be
  rank      : 1 (local_rank: 1)
  exitcode  : 2 (pid: 2711943)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-13_05:09:30
  host      : s16g21.tier2.hpc.kuleuven.be
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 2711942)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
